### PR TITLE
Bug 1111456 - jenkins app default to small gear with enable-jenkins and custom gear size

### PR DESCRIPTION
**Pull request by dinhxuanvu**
When user creates app using rhc with --enable-jenkins and medium --gear-size
options, the jenkins app is deployed onto default small gear size.

The rhc code doesn't pass the gear size option during jenkins app creattion.
This commit will modify the code to allow the gear size value to be passed
into method that create jenkins app.

Bug 1111456
Link <https://bugzilla.redhat.com/show_bug.cgi?id=1111456>

Signed-off-by: Vu Dinh <vdinh@redhat.com>

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
[test]

**Comment by Miciah** [comment]
Are we sure that running Jenkins in a small gear would be a good idea?

**Comment by Miciah** [comment]
Sorry, I got that backwards (before the fix, Jenkins goes on a small gear; after the fix, it goes on a gear of the specified size).

**Comment by Miciah** [comment]
What is the motivation for using a different gear size for Jenkins?

**Comment by dinhxuanvu** [comment]
This is simply a fix to allow the users to create Jenkins app at the gear size of their choice if they choose to do so instead of always forcing it to be small gear (at least this is the motivation of the QE who filed this bug). Also, this fix may be helpful if users intend to keep the Jenkins app to be in the same node of the other apps. For sample, if the setup has 1 small node and 1 medium node, they want to have both apps in medium node instead of one in medium node and the Jenkins app in small node. Or in case the entire multi-node setup in medium size, this flexibility would be help as well.

**Comment by Miciah** [comment]
Before this change, the user has the options of creating the application with a small gear and Jenkins with a small gear, or creating the application with a medium gear and Jenkins with a small gear.  After this change, the user has the options of creating the application with a small gear and Jenkins with a small gear, or creating the application with a medium gear and Jenkins with a medium gear.  So the two questions are the following:

• Do we know that the user will not need to create the application with a medium gear and Jenkins with a small gear?

• Is it important that the user be able to create an application and Jenkins both with medium gears?

**Comment by dinhxuanvu** [comment]
Users certainly have the option to create the jenkins app (independently) with any gear sizes they want (rhc app create jenkins jenkins-1 -g small/medium/large). However, in this case, the jenkins gear is created along side with the other gears using --enable-jenkins (rhc app create app1 python-3.3 --enable-jenkins). If there is already a jenkins app then nothing changes (the jenkins gear doesn't change size at all). If there is no jenkins app already created, then that command will create a jenkins app as well. 

If the users do add --gear-size into the command, it makes sense that the jenkins app should be deployed in the gear-size that is added to the command. Otherwise, the jenkins gear comes out in different size with the other gears which may cause confusion at some points given the fact the users did choose the --gear-size option. 

Eventually, this issue comes down the consistency of the --gear-size option that may be added to the rhc command in my opinion.

**Comment by Miciah** [comment]
@dinhxuanvu, fair enough.  Thanks! The change looks fine to me.  @tiwillia, are you fine with it?

**Comment by tiwillia** [comment]
@dinhxuanvu this change looks good, the only thing I would request you change before we merge is to modify the help page for 'rhc app create' so that it is obvious that the specified gear size will be used.

Perhaps change the current help message:
`  --enable-jenkins [NAME]   Enable Jenkins builds for this application (will create a Jenkins application if not already available). The default name will be 'jenkins' if not specified.`

To something more specific:
`  --enable-jenkins [NAME]   Enable Jenkins builds for this application (will create a Jenkins application if not already available). The default name will be 'jenkins' if not specified. The default gear size will be used unless --gear-size is specified.`

**Comment by dinhxuanvu** [comment]
[test]

**Comment by dinhxuanvu** [comment]
re-[test]

**Comment by dinhxuanvu** [comment]
@tiwillia Fixed and ready for merge :)

**Comment by tiwillia** [comment]
Thanks @dinhxuanvu!

[merge]

**Comment by tiwillia** [comment]
@Miciah could you tag this for merge please? Forgot that I do not have the rights.

**Comment by Miciah** [comment]
openshift-bot, please [merge]!

**Pull request merged**
