### PR TITLE
Improving data provided to users for ha enablement.

### PR DESCRIPTION
**Pull request by sferich888**
Bug 1256952
https://bugzilla.redhat.com/show_bug.cgi?id=1256952

### CODE REVIEW

**Comment by sferich888** [comment]
[test]

**Comment by tiwillia** [comment]
@abhgupta if we put the time into it, we can probably avoid stating the need to scale-up in situations where scale-up isn't necessary by modifying how rhc handles the `enable_ha` action. We can probably duplicate the code from `app_action` in `enable_ha(app)` so that the `rest_app` is available to us for use in a conditional. Do you think its worth the time, or that this is good enough?

**Comment by tiwillia** [comment]
@sferich888 we are currently looking at other ways of resolving this. It would be best not to give this advice if the application does not need to be scaled.

See https://github.com/openshift/rhc/pull/721

**Comment by tiwillia** [comment]
@abhgupta we can go ahead and close this for now, since we are tracking this in another PR.

**Pull request closed without merging**
