### PR TITLE
Bug 1197301 - fixes net-ssh version higher bounds

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
@Miciah let's see how this goes. For some reason bundler was getting lost with `net-ssh` lower boundary and, because other gems like `net-scp` *only* specify a lower boundary, it was trying to fetch `net-ssh 3.0.1`. Which hurts our higher boundary. For better understanding here's the bundler debugging output: https://paste.fedoraproject.org/274212/

**Comment by fabianofranz** [comment]
@jwforres FYI

**Comment by fabianofranz** [comment]
And, and I changed 2.9.3 to 2.9.2 to get rid of 2.9.3.beta1 which also has issues.

**Comment by fabianofranz** [comment]
[merge]

**Comment by Miciah** [comment]
Yay! Thanks, Fabiano!

**Comment by fabianofranz** [comment]
o>

**Pull request merged**
