### PR TITLE
[TO_STAGE] Gemfile and gemspec fixes for net-ssh

### PR DESCRIPTION
**Pull request by Miciah**

### CODE REVIEW

**Comment by Miciah** [comment]
Please [test].

**Comment by Miciah** [comment]
@joelsmith, this PR cherry-picks two commits that modify `Gemfile` and `rhc.gemspec` (along with a Ruby 1.8.7 compatibility fix) and should unblock https://github.com/openshift/origin-server/pull/6310.  Do you have any objections?

**Comment by joelsmith** [comment]
@Miciah no, that's great. Thanks!

**Comment by Miciah** [comment]
openshift-bot, please [merge]!

**Comment by Miciah** [comment]
Thanks, openshift-bot!

**Pull request merged**
