### PR TITLE
README.md contributing fix

### LINKED ISSUE #715: README.md contributing 404 link
The doc [features/README.md](https://github.com/openshift/rhc/blob/master/features/README.md) is missing, which is referenced by [README.md:77](https://github.com/openshift/rhc/blob/master/README.md#developing--contributing).

### PR DESCRIPTION
**Pull request by jsvgoncalves**
- Fixes #715

Signed-off-by: João Gonçalves jsvgoncalves@redhat.com

### CODE REVIEW

**Comment by tiwillia** [comment]
LGTM. @Miciah could you merge this please?

**Comment by Miciah** [comment]
Looks like [`features/README.md`](https://github.com/openshift/rhc/blob/a887e9cbc1aaf80837262c376117b1a96f864788/features/README.md) was renamed to [`cucumber/README.md`](https://github.com/openshift/rhc/blob/9ed27fc334b404c20b914b8e5365c6f3e050179c/cucumber/README.md) in commit 9ed27fc334b404c20b914b8e5365c6f3e050179c.  The same commit adds a deprecation notice regarding cucumber.  However, I believe a significant portion of the content could be salvaged and put into a new `features/README.md` file, and for the cucumber-specific information, it might be useful to add corresponding information for writing RSpec tests.  @fabianofranz, what do you think?

**Comment by fabianofranz** [comment]
@Miciah makes sense to me. At some point we stopped writing Cucumber tests in favour of RSpec, but there are still a significant amount of them (which are important), and I don't see them all being converted.

**Comment by jsvgoncalves** [comment]
bump. Please either merge or close (and fix appropriately)

**Comment by jsvgoncalves** [comment]
Closing this ;)

**Pull request closed without merging**
