### PR TITLE
[TO_STAGE] Fixes dependency issues

### PR DESCRIPTION
**Pull request by thrasher-redhat**
Pulls in recent commit to fix dependency issues that prevent rhc from building.

### CODE REVIEW

**Comment by thrasher-redhat** [comment]
[test]

**Comment by tiwillia** [comment]
LGTM :+1: :confetti_ball: :tada:

**Comment by thrasher-redhat** [comment]
Re[test] to see if this is a fluke.  Building it on 1.9.3 succeeded and manually running the tests resulted in a pass.

**Comment by thrasher-redhat** [comment]
@wshearn The last couple of stage PRs ran into the same issue we're seeing with travis and Ruby 1.9.3.  Did we just force it?

https://travis-ci.org/openshift/rhc/branches

**Comment by wshearn** [comment]
[merge]

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
